// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpGql4NZ33_n19n9ePVEyBt87EqJQVwDw',
    appId: '1:30473385008:web:dbb836873aed892fc669f5',
    messagingSenderId: '30473385008',
    projectId: 'prasang-880a6',
    authDomain: 'prasang-880a6.firebaseapp.com',
    storageBucket: 'prasang-880a6.appspot.com',
    measurementId: 'G-RQW5HZ233N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDifoheTGWRc9eiKSp1c8Cb9ypvVvi4s_4',
    appId: '1:30473385008:android:29bf4e590e04bb65c669f5',
    messagingSenderId: '30473385008',
    projectId: 'prasang-880a6',
    storageBucket: 'prasang-880a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVIW9Fphq0DDQJCS7PMSVueHzd9HeENH4',
    appId: '1:30473385008:ios:b342103c4ff12d80c669f5',
    messagingSenderId: '30473385008',
    projectId: 'prasang-880a6',
    storageBucket: 'prasang-880a6.appspot.com',
    iosClientId: '30473385008-0k27c7aj9im0vqhebbrfkdbq7bu7eum4.apps.googleusercontent.com',
    iosBundleId: 'com.bimsina.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVIW9Fphq0DDQJCS7PMSVueHzd9HeENH4',
    appId: '1:30473385008:ios:b342103c4ff12d80c669f5',
    messagingSenderId: '30473385008',
    projectId: 'prasang-880a6',
    storageBucket: 'prasang-880a6.appspot.com',
    iosClientId: '30473385008-0k27c7aj9im0vqhebbrfkdbq7bu7eum4.apps.googleusercontent.com',
    iosBundleId: 'com.bimsina.notesApp',
  );
}
